##==================##
##       Taps       ##
##==================##

# Core Taps
tap "homebrew/core"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/bundle"

# Command Extension Taps
tap "superatomic/bundle-extensions"

# Third-Party Taps
tap "coursier/formulas"
tap "heroku/brew"
tap "superatomic/xshe"

##==================##
##     Formulae     ##
##==================##

# Programming Languages
brew "python@3.10"
brew "python-tk@3.10"
brew "ruby"
brew "coursier/formulas/coursier"

# Shells
brew "bash"
brew "zsh"
brew "fish"
brew "elvish"

# Shell Additions
brew "starship"
brew "xshe"
brew "zsh-syntax-highlighting"
brew "fisher"
brew "thefuck"

# Command Line Tools
brew "bat"
brew "exa"
brew "micro"
brew "ffmpeg"
brew "imagemagick"
brew "rm-improved"
brew "trash" # Note: macOS only!
brew "pup"
brew "jq"
brew "git"
brew "gh"
brew "httpie"
brew "yt-dlp"
brew "tree"
brew "tldr"
brew "poetry"
brew "ptpython"
brew "colordiff"
brew "neofetch"
brew "cmatrix"

# Other Brews
brew "gnupg"
brew "pinentry-mac"
brew "heroku/brew/heroku"
brew "openssl@3"
brew "portaudio"
brew "pv"
brew "sox"
brew "sphinx-doc"

##==================##
##    Brew Casks    ##
##==================##

# Monospace Fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-hack-nerd-font"

# Character Fonts
cask "font-noto-emoji"

# QuickLook Extensions
cask "qlmarkdown", args: { no_quarantine: true, require_sha: true, appdir: "/Applications/Utilities/" }
cask "syntax-highlight", args: { no_quarantine: true, require_sha: true, appdir: "/Applications/Utilities/" }

# Utilities
cask "iterm2"
cask "eul", args: { appdir: "/Applications/Utilities/" }
cask "iina"
cask "balenaetcher"
cask "cakebrew"
cask "latest"

# Image Manipulators
cask "gimp"
cask "inkscape"
cask "krita"

# Code Editors
cask "jetbrains-toolbox"
cask "vscodium", args: { no_quarantine: true, require_sha: true }

# Text Processing
cask "obsidian"
cask "typora"
cask "textmate"
cask "noto"

# Other Applications
cask "librewolf", args: { no_quarantine: true, require_sha: true }
cask "element"
cask "godot"
