# Core Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# Third-Party Taps
tap "coursier/formulas"
tap "heroku/brew"
tap "superatomic/xshe"
tap "superatomic/bundle-extensions"


# Programming Languages
brew "python@3.8"
brew "python@3.10"
brew "ruby"
brew "coursier/formulas/coursier"
brew "vlang"

# Shell
brew "starship"
brew "xshe"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "fish"
brew "fisher"
brew "elvish"

# Command Line Tools
brew "bat"
brew "exa"
brew "micro"
brew "gh"
brew "git"
brew "poetry"
brew "ptpython"
brew "ffmpeg"
brew "imagemagick"
brew "tree"
brew "tldr"
brew "cmatrix"
brew "httpie"
brew "yt-dlp"
brew "neofetch"
brew "pup"
brew "jq"
brew "heroku/brew/heroku"

# Other brews
brew "gnupg"
brew "pinentry-mac"
brew "openssl@3"
brew "portaudio"
brew "pv"
brew "sox"
brew "sphinx-doc"
brew "swig"
brew "thefuck"

# Fonts
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-hack-nerd-font"

cask "font-noto-emoji"

# QuickLook
cask "qlmarkdown", args: { no_quarantine: true, require_sha: true, appdir: "/Applications/Utilities/" }
cask "syntax-highlight", args: { no_quarantine: true, require_sha: true, appdir: "/Applications/Utilities/" }

# Applications
cask "eul", args: { appdir: "/Applications/Utilities/" }
cask "iina"
cask "balenaetcher"
cask "iterm2"
cask "cakebrew"

cask "jetbrains-toolbox"
cask "vscodium", args: { no_quarantine: true }

cask "gimp"
cask "inkscape"
cask "krita"

cask "librewolf", args: { no_quarantine: true }
cask "element"

cask "obsidian"
cask "typora"
cask "textmate"
cask "noto"

cask "godot"
