
format = "$all$fill$sudo$cmd_duration$jobs$battery$time$status$line_break$character"
right_format = "$shell"

[character]
success_symbol = "[❯](bold cyan)"
error_symbol = "[❯](bold red)"

[fill]
symbol = " "

[directory]
style = "bold blue"
truncation_length = 10
home_symbol = "~"
truncation_symbol = "…/"
truncate_to_repo = false
read_only = " "

[shell]
disabled = false
format = " [$indicator]($style)"
fish_indicator = ""  # Default shell displays nothing.
unknown_indicator = "?sh"
style = "dimmed white"

[python]
symbol = " "
python_binary = ["python3"]  # Ignore python 2

[status]
disabled = false
format = " [$maybe_int $symbol$common_meaning$signal_name]($style) "
success_symbol = ""
not_executable_symbol = ""
not_found_symbol = ""
sigint_symbol = ""
signal_symbol = "⚡"
pipestatus = true
map_symbol = true

[ruby]
symbol = " "

# The following is pasted from https://starship.rs/presets/nerd-font.html

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[rust]
symbol = " "
