#############################################################
# Cross-Shell Environment Variable Configuration using Xshe #
#            https://github.com/superatomic/xshe            #
#############################################################

DOTFILE_DIR = "~/.dotfiles"

# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
XDG_CONFIG_HOME = "~/.config"
XDG_DATA_HOME = "~/.local/share"
XDG_STATE_HOME = "~/.local/state"
XDG_CACHE_HOME = "~/.cache"

BIN_HOME = "~/.local/bin"

# Rust
CARGO_HOME = "$XDG_DATA_HOME/cargo"
RUSTUP_HOME = "$XDG_DATA_HOME/rustup"

# V
VCACHE = "$XDG_CACHE_HOME/vmodules"

PATH = [
    # Development tools
	"$CARGO_HOME/bin",
	"~/Library/Application Support/Coursier/bin",
	"/usr/local/opt/python@3.10/bin",

    # Local bin
    "$BIN_HOME",
    "$BIN_HOME/iterm2",
    
    "$PATH",
]

# https://unix.stackexchange.com/questions/145250/where-is-bashs-history-stored
HISTFILE.bash = "$XDG_STATE_HOME/bash_history"
HISTFILE.zsh = "$XDG_STATE_HOME/zsh_history"

# Zsh
ZDOTDIR.zsh = "$XDG_CONFIG_HOME/zsh"
ZSH_COMPDUMP.zsh = "$XDG_CACHE_HOME/zsh/zcompdump"
ZSH_CACHE_DIR.zsh = "$XDG_CACHE_HOME/oh-my-zsh"

ZSH.zsh = "$XDG_DATA_HOME/oh-my-zsh"  # Path to oh-my-zsh installation.

# Fish
fish_greeting.fish = ""

# Homebrew
HOMEBREW_BUNDLE_FILE = "$DOTFILE_DIR/brew/Brewfile"
HOMEBREW_BAT = "1"
HOMEBREW_NO_INSTALL_CLEANUP = "0"
HOMEBREW_INSTALL_BADGE = "▶︎"
HOMEBREW_NO_ANALYTICS = "1"
HOMEBREW_BUNDLE_NO_LOCK = "1"

# GnuPG
GNUPGHOME = "$XDG_DATA_HOME/gnupg"
GPG_TTY = "$(tty)"

# Fix for https://superuser.com/a/414953
DISABLE_AUTO_TITLE="true"

# https://superuser.com/questions/82123/
__CF_USER_TEXT_ENCODING = "0x0:0:0"

# Python
PYTHONSTARTUP = "$XDG_CONFIG_HOME/pythonrc.py"

# Platform IO
PLATFORMIO_CORE_DIR = "$XDG_DATA_HOME/platformio"  # It's kind of a cache, but it's also other stuff.

# Editor
EDITOR = "$(which micro)"

# Less
LESSHISTFILE = "$XDG_STATE_HOME/lesshst"

# Make more things follow the XDG Standard
# Thanks to https://github.com/b3nj5m1n/xdg-ninja for providing hints for what to do!
ANDROID_HOME = "$XDG_DATA_HOME/android"
GRADLE_USER_HOME = "$XDG_DATA_HOME/gradle"

GEM_HOME = "$XDG_DATA_HOME/gem"
GEM_SPEC_CACHE = "$XDG_CACHE_HOME/gem"

BUNDLE_USER_CONFIG = "$XDG_CONFIG_HOME/bundle"
BUNDLE_USER_CACHE = "$XDG_CACHE_HOME/bundle"
BUNDLE_USER_PLUGIN = "$XDG_DATA_HOME/bundle"

# Colors
# Help from https://stackoverflow.com/questions/4332478/read-the-current-text-color-in-a-xterm/4332530#4332530
BLACK = "$([ -t 0 ] && tput setaf 0)"
RED = "$([ -t 0 ] && tput setaf 1)"
GREEN = "$([ -t 0 ] && tput setaf 2)"
YELLOW = "$([ -t 0 ] && tput setaf 3)"
BLUE = "$([ -t 0 ] && tput setaf 4)"
MAGENTA = "$([ -t 0 ] && tput setaf 5)"
CYAN = "$([ -t 0 ] && tput setaf 6)"
WHITE = "$([ -t 0 ] && tput setaf 7)"
BRIGHT = "$([ -t 0 ] && tput bold)"
UNDERLINE = "$([ -t 0 ] && tput smul)"
REVERSE = "$([ -t 0 ] && tput smso)"
NORMAL = "$([ -t 0 ] && tput sgr0)"
