eval "$(/usr/bin/env xshe bash)"

# Homebrew command-not-found
HB_CNF_HANDLER="$(brew --repository)/Library/Taps/homebrew/homebrew-command-not-found/handler.sh"
if [ -f "$HB_CNF_HANDLER" ]; then
  source "$HB_CNF_HANDLER";
fi

tere() {
    local result=$(command tere "$@")
    [ -n "$result" ] && cd -- "$result"
}

source "$XDG_DATA_HOME"/iterm2_shell_integration.bash
