export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.local/share
export XDG_STATE_HOME=~/.local/state
export XDG_CACHE_HOME=~/.cache

# https://unix.stackexchange.com/questions/145250/where-is-bashs-history-stored
export HISTFILE=$XDG_STATE_HOME/bash_history
